<?php

namespace Container0LpDo3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerDureePromoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wDQhkOm.App\Controller\HomeController::DureePromo()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wDQhkOm.App\\Controller\\HomeController::DureePromo()'] = ($container->privates['.service_locator.wDQhkOm'] ?? $container->load('get_ServiceLocator_WDQhkOmService'))->withContext('App\\Controller\\HomeController::DureePromo()', $container);
    }
}
