<?php

namespace Container0LpDo3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t2vqdVg.App\Controller\HomeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t2vqdVg.App\\Controller\\HomeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'cardRepository' => ['privates', 'App\\Repository\\CardRepository', 'getCardRepositoryService', true],
            'promoDynamique' => ['privates', 'App\\Repository\\PromoDynamiqueRepository', 'getPromoDynamiqueRepositoryService', true],
        ], [
            'productRepository' => 'App\\Repository\\ProductRepository',
            'cardRepository' => 'App\\Repository\\CardRepository',
            'promoDynamique' => 'App\\Repository\\PromoDynamiqueRepository',
        ]))->withContext('App\\Controller\\HomeController::index()', $container);
    }
}
