<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'DetailPromo' => [parent::class, 'DetailPromo', null],
        "\0".parent::class."\0".'EnPromotion' => [parent::class, 'EnPromotion', null],
        "\0".parent::class."\0".'ImageUrl' => [parent::class, 'ImageUrl', null],
        "\0".parent::class."\0".'ImageUrl1' => [parent::class, 'ImageUrl1', null],
        "\0".parent::class."\0".'ImageUrl2' => [parent::class, 'ImageUrl2', null],
        "\0".parent::class."\0".'ImageUrl3' => [parent::class, 'ImageUrl3', null],
        "\0".parent::class."\0".'ImageUrl4' => [parent::class, 'ImageUrl4', null],
        "\0".parent::class."\0".'ImageUrl5' => [parent::class, 'ImageUrl5', null],
        "\0".parent::class."\0".'ImageUrl6' => [parent::class, 'ImageUrl6', null],
        "\0".parent::class."\0".'ImageUrlDump1' => [parent::class, 'ImageUrlDump1', null],
        "\0".parent::class."\0".'ImageUrlDump2' => [parent::class, 'ImageUrlDump2', null],
        "\0".parent::class."\0".'ImageUrlDump3' => [parent::class, 'ImageUrlDump3', null],
        "\0".parent::class."\0".'NonCollection' => [parent::class, 'NonCollection', null],
        "\0".parent::class."\0".'SlidePromo' => [parent::class, 'SlidePromo', null],
        "\0".parent::class."\0".'addAt' => [parent::class, 'addAt', null],
        "\0".parent::class."\0".'admin' => [parent::class, 'admin', null],
        "\0".parent::class."\0".'cards' => [parent::class, 'cards', null],
        "\0".parent::class."\0".'couleur' => [parent::class, 'couleur', null],
        "\0".parent::class."\0".'description1' => [parent::class, 'description1', null],
        "\0".parent::class."\0".'description2' => [parent::class, 'description2', null],
        "\0".parent::class."\0".'description3' => [parent::class, 'description3', null],
        "\0".parent::class."\0".'description4' => [parent::class, 'description4', null],
        "\0".parent::class."\0".'discountPrice' => [parent::class, 'discountPrice', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'libele' => [parent::class, 'libele', null],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null],
        "\0".parent::class."\0".'quantite' => [parent::class, 'quantite', null],
        "\0".parent::class."\0".'section' => [parent::class, 'section', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'taille' => [parent::class, 'taille', null],
        "\0".parent::class."\0".'type_produit' => [parent::class, 'type_produit', null],
        'DetailPromo' => [parent::class, 'DetailPromo', null],
        'EnPromotion' => [parent::class, 'EnPromotion', null],
        'ImageUrl' => [parent::class, 'ImageUrl', null],
        'ImageUrl1' => [parent::class, 'ImageUrl1', null],
        'ImageUrl2' => [parent::class, 'ImageUrl2', null],
        'ImageUrl3' => [parent::class, 'ImageUrl3', null],
        'ImageUrl4' => [parent::class, 'ImageUrl4', null],
        'ImageUrl5' => [parent::class, 'ImageUrl5', null],
        'ImageUrl6' => [parent::class, 'ImageUrl6', null],
        'ImageUrlDump1' => [parent::class, 'ImageUrlDump1', null],
        'ImageUrlDump2' => [parent::class, 'ImageUrlDump2', null],
        'ImageUrlDump3' => [parent::class, 'ImageUrlDump3', null],
        'NonCollection' => [parent::class, 'NonCollection', null],
        'SlidePromo' => [parent::class, 'SlidePromo', null],
        'addAt' => [parent::class, 'addAt', null],
        'admin' => [parent::class, 'admin', null],
        'cards' => [parent::class, 'cards', null],
        'couleur' => [parent::class, 'couleur', null],
        'description1' => [parent::class, 'description1', null],
        'description2' => [parent::class, 'description2', null],
        'description3' => [parent::class, 'description3', null],
        'description4' => [parent::class, 'description4', null],
        'discountPrice' => [parent::class, 'discountPrice', null],
        'id' => [parent::class, 'id', null],
        'libele' => [parent::class, 'libele', null],
        'prix' => [parent::class, 'prix', null],
        'quantite' => [parent::class, 'quantite', null],
        'section' => [parent::class, 'section', null],
        'slug' => [parent::class, 'slug', null],
        'taille' => [parent::class, 'taille', null],
        'type_produit' => [parent::class, 'type_produit', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
