<?php

namespace ContainerQJQ7XR5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WDQhkOmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wDQhkOm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wDQhkOm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'promoDynamiqueRepository' => ['privates', 'App\\Repository\\PromoDynamiqueRepository', 'getPromoDynamiqueRepositoryService', true],
        ], [
            'promoDynamiqueRepository' => 'App\\Repository\\PromoDynamiqueRepository',
        ]);
    }
}
