<?php

namespace ContainerQJQ7XR5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SmZ3qYSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SmZ3qYS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SmZ3qYS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.IPsjuf5.App\\Controller\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\CartController::deleteProduct' => ['privates', '.service_locator.pmZk7Hr.App\\Controller\\CartController::deleteProduct()', 'getCartControllerdeleteProductService', true],
            'App\\Controller\\CartController::countUserCartItems' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\CartController::countUserCartItems()', 'getCartControllercountUserCartItemsService', true],
            'App\\Controller\\CartController::compteur' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\CartController::compteur()', 'getCartControllercompteurService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.7oRkZNB.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\FormulaireInscriptionController::createUser' => ['privates', '.service_locator.__CzQUd.App\\Controller\\FormulaireInscriptionController::createUser()', 'getFormulaireInscriptionControllercreateUserService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.t2vqdVg.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\HomeController::DureePromo' => ['privates', '.service_locator.wDQhkOm.App\\Controller\\HomeController::DureePromo()', 'getHomeControllerDureePromoService', true],
            'App\\Controller\\HomeController::cookies' => ['privates', '.service_locator.wDQhkOm.App\\Controller\\HomeController::cookies()', 'getHomeControllercookiesService', true],
            'App\\Controller\\LivraisonController::index' => ['privates', '.service_locator.jbYScXs.App\\Controller\\LivraisonController::index()', 'getLivraisonControllerindexService', true],
            'App\\Controller\\NavbarController::navbar' => ['privates', '.service_locator.64trKF3.App\\Controller\\NavbarController::navbar()', 'getNavbarControllernavbarService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.vL9hpCG.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.kf6tjhM.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.dj_NNeV.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\WalletController::index' => ['privates', '.service_locator.0xM3Ob9.App\\Controller\\WalletController::index()', 'getWalletControllerindexService', true],
            'App\\Controller\\WalletController::inde' => ['privates', '.service_locator.q30XUWO.App\\Controller\\WalletController::inde()', 'getWalletControllerindeService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.IPsjuf5.App\\Controller\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\CartController:deleteProduct' => ['privates', '.service_locator.pmZk7Hr.App\\Controller\\CartController::deleteProduct()', 'getCartControllerdeleteProductService', true],
            'App\\Controller\\CartController:countUserCartItems' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\CartController::countUserCartItems()', 'getCartControllercountUserCartItemsService', true],
            'App\\Controller\\CartController:compteur' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\CartController::compteur()', 'getCartControllercompteurService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.7oRkZNB.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\FormulaireInscriptionController:createUser' => ['privates', '.service_locator.__CzQUd.App\\Controller\\FormulaireInscriptionController::createUser()', 'getFormulaireInscriptionControllercreateUserService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.t2vqdVg.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\HomeController:DureePromo' => ['privates', '.service_locator.wDQhkOm.App\\Controller\\HomeController::DureePromo()', 'getHomeControllerDureePromoService', true],
            'App\\Controller\\HomeController:cookies' => ['privates', '.service_locator.wDQhkOm.App\\Controller\\HomeController::cookies()', 'getHomeControllercookiesService', true],
            'App\\Controller\\LivraisonController:index' => ['privates', '.service_locator.jbYScXs.App\\Controller\\LivraisonController::index()', 'getLivraisonControllerindexService', true],
            'App\\Controller\\NavbarController:navbar' => ['privates', '.service_locator.64trKF3.App\\Controller\\NavbarController::navbar()', 'getNavbarControllernavbarService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.vL9hpCG.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.kf6tjhM.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.dj_NNeV.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\WalletController:index' => ['privates', '.service_locator.0xM3Ob9.App\\Controller\\WalletController::index()', 'getWalletControllerindexService', true],
            'App\\Controller\\WalletController:inde' => ['privates', '.service_locator.q30XUWO.App\\Controller\\WalletController::inde()', 'getWalletControllerindeService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::deleteProduct' => '?',
            'App\\Controller\\CartController::countUserCartItems' => '?',
            'App\\Controller\\CartController::compteur' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\FormulaireInscriptionController::createUser' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::DureePromo' => '?',
            'App\\Controller\\HomeController::cookies' => '?',
            'App\\Controller\\LivraisonController::index' => '?',
            'App\\Controller\\NavbarController::navbar' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\WalletController::index' => '?',
            'App\\Controller\\WalletController::inde' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:deleteProduct' => '?',
            'App\\Controller\\CartController:countUserCartItems' => '?',
            'App\\Controller\\CartController:compteur' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\FormulaireInscriptionController:createUser' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:DureePromo' => '?',
            'App\\Controller\\HomeController:cookies' => '?',
            'App\\Controller\\LivraisonController:index' => '?',
            'App\\Controller\\NavbarController:navbar' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\WalletController:index' => '?',
            'App\\Controller\\WalletController:inde' => '?',
        ]);
    }
}
