<?php

namespace ContainerQJQ7XR5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerdeleteProductService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pmZk7Hr.App\Controller\CartController::deleteProduct()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pmZk7Hr.App\\Controller\\CartController::deleteProduct()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', false],
        ], [
            'em' => '?',
            'csrfTokenManager' => '?',
        ]))->withContext('App\\Controller\\CartController::deleteProduct()', $container);
    }
}
