<?php

namespace ContainerQJQ7XR5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetailsLivraisonTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DetailsLivraisonType' shared autowired service.
     *
     * @return \App\Form\DetailsLivraisonType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DetailsLivraisonType.php';

        return $container->privates['App\\Form\\DetailsLivraisonType'] = new \App\Form\DetailsLivraisonType();
    }
}
