<?php

namespace ContainerQJQ7XR5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavbarControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\NavbarController' shared autowired service.
     *
     * @return \App\Controller\NavbarController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/NavbarController.php';

        $container->services['App\\Controller\\NavbarController'] = $instance = new \App\Controller\NavbarController(($container->services['App\\Controller\\CartController'] ?? $container->load('getCartControllerService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\NavbarController', $container));

        return $instance;
    }
}
