<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOWQbPZ1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOWQbPZ1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOWQbPZ1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOWQbPZ1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOWQbPZ1\App_KernelDevDebugContainer([
    'container.build_hash' => 'OWQbPZ1',
    'container.build_id' => '6d014e3b',
    'container.build_time' => 1732399864,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOWQbPZ1');
